// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/taiwan-calendar/health": {
            "get": {
                "description": "檢查 API 服務是否正常運行",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系統"
                ],
                "summary": "健康檢查",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/taiwan-calendar/{year}": {
            "get": {
                "tags": [
                    "taiwan-calendar"
                ],
                "summary": "取得行事曆資料",
                "parameters": [
                    {
                        "type": "string",
                        "description": "年份 (西元)",
                        "name": "year",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "是否為假日",
                        "name": "isHoliday",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "回傳行事曆資料",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Calendar"
                            }
                        }
                    },
                    "400": {
                        "description": "格式錯誤",
                        "schema": {
                            "$ref": "#/definitions/controller.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "範圍錯誤或是查無資料",
                        "schema": {
                            "$ref": "#/definitions/controller.ErrorResponse"
                        }
                    },
                    "429": {
                        "description": "頂到頻率限制",
                        "schema": {
                            "$ref": "#/definitions/controller.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/taiwan-calendar/{year}/{month}": {
            "get": {
                "tags": [
                    "taiwan-calendar"
                ],
                "summary": "取得行事曆資料",
                "parameters": [
                    {
                        "type": "string",
                        "description": "年份 (西元)",
                        "name": "year",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "月份 (01-12)",
                        "name": "month",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "是否為假日",
                        "name": "isHoliday",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "回傳行事曆資料",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Calendar"
                            }
                        }
                    },
                    "400": {
                        "description": "格式錯誤",
                        "schema": {
                            "$ref": "#/definitions/controller.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "範圍錯誤或是查無資料",
                        "schema": {
                            "$ref": "#/definitions/controller.ErrorResponse"
                        }
                    },
                    "429": {
                        "description": "頂到頻率限制",
                        "schema": {
                            "$ref": "#/definitions/controller.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/taiwan-calendar/{year}/{month}/{day}": {
            "get": {
                "tags": [
                    "taiwan-calendar"
                ],
                "summary": "取得行事曆資料",
                "parameters": [
                    {
                        "type": "string",
                        "description": "年份 (西元)",
                        "name": "year",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "月份 (01-12)",
                        "name": "month",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "日期 (01-31)",
                        "name": "day",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "是否為假日",
                        "name": "isHoliday",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "回傳行事曆資料",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Calendar"
                            }
                        }
                    },
                    "400": {
                        "description": "格式錯誤",
                        "schema": {
                            "$ref": "#/definitions/controller.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "範圍錯誤或是查無資料",
                        "schema": {
                            "$ref": "#/definitions/controller.ErrorResponse"
                        }
                    },
                    "429": {
                        "description": "頂到頻率限制",
                        "schema": {
                            "$ref": "#/definitions/controller.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "controller.ErrorResponse": {
            "type": "object",
            "properties": {
                "http_code": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "string",
                    "example": "error"
                }
            }
        },
        "model.Calendar": {
            "type": "object",
            "properties": {
                "caption": {
                    "type": "string"
                },
                "date": {
                    "type": "string"
                },
                "date_format": {
                    "type": "string"
                },
                "day": {
                    "type": "string"
                },
                "isHoliday": {
                    "type": "boolean"
                },
                "month": {
                    "type": "string"
                },
                "month_en": {
                    "type": "string"
                },
                "month_en_abbr": {
                    "type": "string"
                },
                "roc_year": {
                    "type": "string"
                },
                "week": {
                    "type": "string"
                },
                "week_abbr": {
                    "type": "string"
                },
                "week_chinese": {
                    "type": "string"
                },
                "year": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "127.0.0.1",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "台灣行事曆 API",
	Description:      "台灣行事曆相關的 API 服務，可參考：https://github.com/880831ian/taiwan-calendar",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
